/**
 * GENERATED by `node scripts/nfl/backtest-prop.ts --write-weights` — do not hand-edit.
 *
 * NFL PLAYER PROP EDGE ENGINE fitted distribution parameters (nfl-prop-edge-v1).
 * dispersion fit 2021,2022; evaluated 2023,2024,2025. Calibration entries are out-of-sample (test seasons).
 */

import type { PropModelWeights } from "./weights.ts";

export const NFL_PROP_FITTED_WEIGHTS: PropModelWeights = {
  "version": "nfl-prop-edge-v1",
  "params": {
    "dispersion": {
      "targets": 8,
      "carries": 4,
      "pass_att": 30,
      "qb_carries": 5
    },
    "per_unit_cv": {
      "rec": 0.85,
      "rush": 1.6,
      "pass": 1.05
    },
    "qb_early_exit": {
      "prob": 0.04,
      "fraction": 0.3
    },
    "scale": {
      "targets": 0.9024,
      "catch": 0.9906,
      "carries": 0.9412,
      "qb_carries": 1.0172,
      "pass_att": 0.9538,
      "cmp": 0.9941,
      "ypr": 0.9939,
      "ypc": 0.9739,
      "ypcmp": 1.0193,
      "pass_td": 0.9707,
      "int": 0.9882,
      "td": 0.9195,
      "fg": 1.0328,
      "xp": 0.9489
    }
  },
  "calibration": {
    "fg_made": {
      "pit_ece": 0.0286,
      "over_ece": 0.0203,
      "n": 1449,
      "mae": 1.034
    },
    "xp_made": {
      "pit_ece": 0.0384,
      "over_ece": 0.0311,
      "n": 1449,
      "mae": 1.095
    },
    "kicking_points": {
      "pit_ece": 0.0521,
      "over_ece": 0.023,
      "n": 1449,
      "mae": 3.094
    },
    "pass_yds": {
      "pit_ece": 0.1083,
      "over_ece": 0.0764,
      "n": 1473,
      "mae": 64.859
    },
    "pass_att": {
      "pit_ece": 0.0426,
      "over_ece": 0.0268,
      "n": 1473,
      "mae": 7.446
    },
    "pass_cmp": {
      "pit_ece": 0.0499,
      "over_ece": 0.0422,
      "n": 1473,
      "mae": 5.169
    },
    "pass_tds": {
      "pit_ece": 0.0523,
      "over_ece": 0.0416,
      "n": 1473,
      "mae": 0.89
    },
    "pass_ints": {
      "pit_ece": 0.039,
      "over_ece": 0.0407,
      "n": 1473,
      "mae": 0.679
    },
    "rush_yds": {
      "pit_ece": 0.077,
      "over_ece": 0.0456,
      "n": 3816,
      "mae": 19.258
    },
    "rush_att": {
      "pit_ece": 0.0618,
      "over_ece": 0.0351,
      "n": 3816,
      "mae": 3.229
    },
    "rec_yds": {
      "pit_ece": 0.0316,
      "over_ece": 0.0294,
      "n": 9699,
      "mae": 19.789
    },
    "receptions": {
      "pit_ece": 0.0176,
      "over_ece": 0.0189,
      "n": 9699,
      "mae": 1.481
    },
    "targets": {
      "pit_ece": 0.0231,
      "over_ece": 0.0268,
      "n": 9699,
      "mae": 1.898
    },
    "anytime_td": {
      "pit_ece": 0.0167,
      "over_ece": 0.0356,
      "n": 9699,
      "mae": 0.351
    }
  },
  "trained_on": "dispersion fit 2021,2022; evaluated 2023,2024,2025",
  "fitted_at": "2026-09-22T03:19:32.541Z"
};
