import { useState, useEffect, type ReactNode } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { 
  Shield, EyeOff, FileText, Copyright, 
  Gamepad2, CreditCard, Mail, Trash2, ChevronLeft, X
} from "lucide-react";
import { useNavigate, useLocation } from "react-router-dom";
import TermsContent from "@/components/legal/TermsContent";
import DisclaimerContent from "@/components/legal/DisclaimerContent";
import ResponsibleGamingContent from "@/components/legal/ResponsibleGamingContent";
import RefundContent from "@/components/legal/RefundContent";
import ContactContent from "@/components/legal/ContactContent";
import CopyrightContent from "@/components/legal/CopyrightContent";
import DeleteDataContent from "@/components/legal/DeleteDataContent";

const PrivacyContent = () => (
  <div className="space-y-5 text-xs text-muted-foreground leading-relaxed">
    <p className="text-foreground/80 font-medium">
      Sentinel ("Sentinel," "we," "us," or "our") provides sports analysis, statistical tools, pick-tracking features, market data displays, and related content for <strong className="text-foreground">informational and entertainment purposes</strong>.
    </p>
    <p>This Privacy Policy explains how we collect, use, disclose, and protect information when you use the Sentinel mobile application, website, and related services (collectively, the "Services").</p>
    <p className="text-accent font-semibold">By using Sentinel, you agree to this Privacy Policy.</p>

    <div>
      <h3 className="text-sm font-bold text-foreground mb-2">Information We Collect</h3>
      <p className="mb-2">We may collect information you provide directly to us, including:</p>
      <ul className="list-disc list-inside space-y-1 ml-1">
        <li>Name, username, email address, and login credentials</li>
        <li>Profile information, support requests, and feedback</li>
        <li>Saved picks, watchlists, preferences, notes, and alerts</li>
      </ul>
      <p className="mt-3 mb-2">We may also collect information automatically, including:</p>
      <ul className="list-disc list-inside space-y-1 ml-1">
        <li>Device type, operating system, app version, language, and time zone</li>
        <li>Log data, crash data, diagnostics, and performance data</li>
        <li>Usage information and approximate location derived from IP address where permitted by law</li>
      </ul>
      <p className="mt-3">We may receive information from third parties such as analytics providers, authentication providers, payment processors, and sports data or odds providers.</p>
    </div>

    <div>
      <h3 className="text-sm font-bold text-foreground mb-2">How We Use Information</h3>
      <p className="mb-2">We may use information to:</p>
      <ul className="list-disc list-inside space-y-1 ml-1">
        <li>Provide, operate, maintain, and improve Sentinel</li>
        <li>Create and manage accounts</li>
        <li>Deliver analytics and alerts</li>
        <li>Process subscriptions and respond to support requests</li>
        <li>Monitor performance and prevent fraud or abuse</li>
        <li>Send account and billing notices</li>
        <li>Enforce our Terms and comply with legal obligations</li>
      </ul>
    </div>

    <div>
      <h3 className="text-sm font-bold text-foreground mb-2">How We Share Information</h3>
      <p className="mb-2">We may share information with:</p>
      <ul className="list-disc list-inside space-y-1 ml-1">
        <li>Service providers that help us operate Sentinel (hosting, analytics, authentication, customer support, payment vendors, infrastructure vendors)</li>
        <li>Professional advisors, regulators, law enforcement, or transaction-related parties where required by law</li>
      </ul>
      <p className="mt-3 font-semibold text-foreground">We do not sell personal information for money.</p>
    </div>

    <div>
      <h3 className="text-sm font-bold text-foreground mb-2">Sports Data, Odds, Picks & Predictions</h3>
      <p className="mb-2">Sentinel may display odds, lines, historical results, projections, trends, model outputs, and pick-related content. This information may come from third-party providers or be generated by Sentinel systems.</p>
      <p className="mb-2">This information may be <strong className="text-foreground">delayed, incomplete, or inaccurate</strong> and may change without notice.</p>
      <p className="text-accent/80 font-medium">All such information is provided for informational and entertainment purposes only. Sentinel does not guarantee the accuracy, completeness, profitability, or outcome of any information, analysis, projection, or pick displayed in the app.</p>
    </div>

    <div>
      <h3 className="text-sm font-bold text-foreground mb-2">No Gambling, Betting, or Financial Advice</h3>
      <ul className="list-disc list-inside space-y-1 ml-1">
        <li>Sentinel does <strong className="text-foreground">not</strong> provide gambling advice, financial advice, legal advice, tax advice, or investment advice</li>
        <li>Sentinel does <strong className="text-foreground">not</strong> guarantee winnings, profits, or success</li>
        <li>Any decision made based on Sentinel is made solely at the user's own risk</li>
        <li>Sentinel is <strong className="text-foreground">not</strong> a sportsbook, bookmaker, casino, or gambling operator and does not accept or process wagers unless expressly stated otherwise</li>
      </ul>
    </div>

    <div>
      <h3 className="text-sm font-bold text-foreground mb-2">Age Restrictions</h3>
      <p>Sentinel is intended only for users who are at least <strong className="text-foreground">18 years old</strong>, and any higher age required by the laws of their jurisdiction. If you do not meet the minimum legal age, do not use Sentinel.</p>
    </div>

    <div>
      <h3 className="text-sm font-bold text-foreground mb-2">Data Retention</h3>
      <p>We retain information for as long as reasonably necessary to provide the Services, comply with legal obligations, resolve disputes, enforce agreements, and maintain business records.</p>
    </div>

    <div>
      <h3 className="text-sm font-bold text-foreground mb-2">Security</h3>
      <p>We use reasonable administrative, technical, and organizational safeguards designed to protect information. However, no method of transmission or storage is completely secure, and we cannot guarantee absolute security.</p>
    </div>

    <div>
      <h3 className="text-sm font-bold text-foreground mb-2">Your Rights & Choices</h3>
      <p className="mb-2">Depending on your location, you may have rights to:</p>
      <ul className="list-disc list-inside space-y-1 ml-1">
        <li>Access, correct, delete, or restrict the processing of your personal information</li>
        <li>Withdraw consent where applicable</li>
      </ul>
      <p className="mt-2">To make a request, contact us at <a href="mailto:privacy@sentinelprops.com" className="text-accent hover:underline">privacy@sentinelprops.com</a></p>
    </div>

    <div>
      <h3 className="text-sm font-bold text-foreground mb-2">Third-Party Services & Links</h3>
      <p>Sentinel may contain links to third-party websites, sportsbooks, affiliates, partners, or services. We are not responsible for the privacy, content, accuracy, legality, or practices of third parties. Your use of third-party services is governed by their own terms and privacy policies.</p>
    </div>

    <div>
      <h3 className="text-sm font-bold text-foreground mb-2">Children's Privacy</h3>
      <p>Sentinel is not directed to children and we do not knowingly collect personal information from children under the minimum legal age.</p>
    </div>

    <div>
      <h3 className="text-sm font-bold text-foreground mb-2">Changes to This Privacy Policy</h3>
      <p>We may update this Privacy Policy from time to time. We will post the updated version and update the "Last updated" date. Continued use of Sentinel after changes become effective means you accept the revised Policy to the extent permitted by law.</p>
    </div>

    <div className="pt-2 border-t border-border/40">
      <h3 className="text-sm font-bold text-foreground mb-2">Contact Us</h3>
      <p>For privacy questions or requests, contact:</p>
      <div className="mt-2 bg-secondary/40 rounded-xl p-3">
        <p className="font-bold text-foreground">Sentinel</p>
        <p>Email & Support: <a href="mailto:privacy@sentinelprops.com" className="text-accent hover:underline">privacy@sentinelprops.com</a></p>
      </div>
    </div>
  </div>
);

interface LegalSection {
  id: string;
  title: string;
  subtitle: string;
  icon: typeof EyeOff;
  gradient: string;
  content: ReactNode | null;
}

const LEGAL_SECTIONS: LegalSection[] = [
  {
    id: "privacy",
    title: "Privacy Policy",
    subtitle: "How we handle your data",
    icon: EyeOff,
    gradient: "from-violet-500 to-purple-600",
    content: <PrivacyContent />,
  },
  {
    id: "terms",
    title: "Terms of Use",
    subtitle: "Rules for using Sentinel",
    icon: FileText,
    gradient: "from-blue-500 to-cyan-500",
    content: <TermsContent />,
  },
  {
    id: "disclaimer",
    title: "Legal Disclaimer",
    subtitle: "Important legal information",
    icon: Shield,
    gradient: "from-amber-500 to-orange-500",
    content: <DisclaimerContent />,
  },
  {
    id: "responsible-gaming",
    title: "Responsible Gaming",
    subtitle: "Play smart, bet responsibly",
    icon: Gamepad2,
    gradient: "from-emerald-500 to-green-600",
    content: <ResponsibleGamingContent />,
  },
  {
    id: "refund",
    title: "Refund Policy",
    subtitle: "Refund & cancellation info",
    icon: CreditCard,
    gradient: "from-pink-500 to-rose-500",
    content: <RefundContent />,
  },
  {
    id: "contact",
    title: "Contact / Support",
    subtitle: "Get in touch with us",
    icon: Mail,
    gradient: "from-sky-500 to-blue-500",
    content: <ContactContent />,
  },
  {
    id: "copyright",
    title: "Copyright Policy",
    subtitle: "Intellectual property rights",
    icon: Copyright,
    gradient: "from-indigo-500 to-violet-500",
    content: <CopyrightContent />,
  },
  {
    id: "delete-data",
    title: "Delete Account / Data",
    subtitle: "Request data deletion",
    icon: Trash2,
    gradient: "from-red-500 to-rose-600",
    content: <DeleteDataContent />,
  },
];

const LegalPage = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const [activeSection, setActiveSection] = useState<string | null>(null);

  // Auto-open section when navigated from footer
  useEffect(() => {
    const state = location.state as { section?: string } | null;
    if (state?.section) {
      setActiveSection(state.section);
      // Clear the state so back navigation doesn't re-trigger
      window.history.replaceState({}, "");
    }
  }, [location.state]);

  const active = LEGAL_SECTIONS.find((s) => s.id === activeSection);

  return (
    <div className="min-h-screen pb-safe-plus-4 pt-safe-plus-2">
      {/* Header */}
      <div className="px-5 pt-6 pb-4 flex items-center gap-3">
        <button
          onClick={() => (activeSection ? setActiveSection(null) : navigate(-1))}
          className="w-9 h-9 rounded-xl bg-card border border-border flex items-center justify-center hover:bg-secondary transition-colors"
        >
          <ChevronLeft className="w-4 h-4 text-foreground" />
        </button>
        <div>
          <h1 className="text-lg font-bold text-foreground">
            {activeSection ? active?.title : "Legal & Policies"}
          </h1>
          <p className="text-[11px] text-muted-foreground">
            {activeSection ? active?.subtitle : "Everything you need to know"}
          </p>
        </div>
      </div>

      <AnimatePresence mode="wait">
        {!activeSection ? (
          <motion.div
            key="grid"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0, x: -20 }}
            transition={{ duration: 0.25 }}
            className="px-5 grid grid-cols-2 gap-3"
          >
            {LEGAL_SECTIONS.map((section, i) => {
              const Icon = section.icon;
              return (
                <motion.button
                  key={section.id}
                  initial={{ opacity: 0, y: 20, scale: 0.95 }}
                  animate={{ opacity: 1, y: 0, scale: 1 }}
                  transition={{ delay: i * 0.05, duration: 0.4, ease: [0.25, 0.46, 0.45, 0.94] }}
                  whileHover={{ scale: 1.03, y: -2 }}
                  whileTap={{ scale: 0.97 }}
                  onClick={() => setActiveSection(section.id)}
                  className="vision-card p-4 flex flex-col items-center gap-3 text-center group"
                >
                  <div
                    className={`w-12 h-12 rounded-xl bg-gradient-to-br ${section.gradient} flex items-center justify-center shadow-lg group-hover:shadow-xl transition-all group-hover:scale-110`}
                    style={{ boxShadow: "0 4px 14px -3px hsla(228, 20%, 0%, 0.35)" }}
                  >
                    <Icon className="w-5.5 h-5.5 text-white" />
                  </div>
                  <div>
                    <p className="text-xs font-bold text-foreground leading-tight">{section.title}</p>
                    <p className="text-[10px] text-muted-foreground mt-0.5 leading-snug">{section.subtitle}</p>
                  </div>
                </motion.button>
              );
            })}
          </motion.div>
        ) : (
          <motion.div
            key="detail"
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: 20 }}
            transition={{ duration: 0.25 }}
            className="px-5"
          >
            <div className="vision-card p-4 overflow-hidden">
              <div className="flex items-center gap-3 mb-4 min-w-0">
                {active && (
                  <div
                    className={`w-10 h-10 rounded-xl bg-gradient-to-br ${active.gradient} flex items-center justify-center shadow-md flex-shrink-0`}
                  >
                    <active.icon className="w-5 h-5 text-white" />
                  </div>
                )}
                <div className="flex-1 min-w-0">
                  <h2 className="text-sm font-bold text-foreground truncate">{active?.title}</h2>
                  <p className="text-[10px] text-muted-foreground truncate">{active?.subtitle}</p>
                </div>
                <button
                  onClick={() => setActiveSection(null)}
                  className="w-8 h-8 rounded-lg bg-input border border-border flex items-center justify-center hover:bg-secondary transition-colors flex-shrink-0"
                >
                  <X className="w-3.5 h-3.5 text-muted-foreground" />
                </button>
              </div>

              <div className="text-sm text-muted-foreground leading-relaxed">
                {active?.content ? (
                  active.content
                ) : (
                  <div className="py-8 text-center">
                    <p className="text-muted-foreground/60 text-xs">Content coming soon.</p>
                    <p className="text-muted-foreground/40 text-[10px] mt-1">This section is being prepared.</p>
                  </div>
                )}
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};

export default LegalPage;
