/**
 * NFL GAME EDGE ENGINE — model version, weights contract and fixed priors.
 *
 * Fitted coefficients live in `weights_fitted.ts`, which is GENERATED by
 * `node scripts/nfl/backtest-game.ts --write-weights` (walk-forward ridge fits
 * on nflverse history). Do not hand-edit that file; bump
 * `NFL_GAME_MODEL_VERSION` whenever it is regenerated so predictions,
 * calibration and backtests stay tied to an immutable version.
 *
 * Nothing in this file is shared with the player-prop engine.
 */

import type { LinearModel } from "./fit.ts";

export const NFL_GAME_MODEL_VERSION = "nfl-game-edge-v1";

export interface PlattParams {
  a: number;
  b: number;
}

/**
 * Per-market evidence from the walk-forward backtest: the smallest edge
 * threshold at which gated bets were profitable (n ≥ 75). `null` means the
 * backtest found NO profitable threshold — the market stays NO PLAY while
 * `respect_backtest_evidence` is on. This can only withhold picks, never add them.
 */
export interface EvidenceGate {
  min_edge: number; // 0..1
  bets: number;
  roi: number;
}

export type GameMarketKey = "moneyline" | "spread" | "total";

export interface GameModelWeights {
  version: string;
  /** Home-minus-away margin model (points). */
  margin: LinearModel;
  margin_sd: number;
  margin_key_weights: Record<number, number>;
  /** Home win-probability model (logistic). Separate coefficients from `margin`. */
  moneyline: LinearModel;
  /** Game total model; target is total − 2 × league points/game. */
  total: LinearModel;
  total_sd: number;
  total_key_weights: Record<number, number>;
  /** Out-of-sample Platt calibration per market (null = not yet fit). */
  calibration: { moneyline: PlattParams | null; spread: PlattParams | null; total: PlattParams | null };
  evidence_gates: Record<GameMarketKey, EvidenceGate | null>;
  trained_on: string;
  fitted_at: string;
}

/**
 * Factor 25 (market movement) has no history in nflverse (closing lines only),
 * so it cannot be fit. It enters as a small, capped prior: the model leans a
 * fraction of the way toward where the market moved, never all the way.
 */
export const MARKET_MOVEMENT_PRIOR = {
  /** Points of projected margin per point of home-spread movement. */
  spread_points_per_point: 0.25,
  spread_cap_points: 1.0,
  /** Points of projected total per point of total movement. */
  total_points_per_point: 0.25,
  total_cap_points: 1.5,
  /** Logit shift per unit of no-vig home-probability movement. */
  ml_logit_per_prob: 1.0,
  ml_cap_logit: 0.12,
} as const;

/**
 * `game_confidence` component weights (sum = 1). Separate from — and never
 * blended with — the prop engine's `prop_confidence` weights.
 */
export const GAME_CONFIDENCE_WEIGHTS = {
  probability: 0.1,
  edge: 0.2,
  data_quality: 0.15,
  stability: 0.1,
  injury_certainty: 0.1,
  liquidity: 0.1,
  agreement: 0.1,
  calibration: 0.15,
} as const;

/** Margin / total support for the discrete PMFs. */
export const MARGIN_RANGE = { lo: -80, hi: 80 } as const;
export const TOTAL_RANGE = { lo: 0, hi: 130 } as const;
